### ISSUE TITLE
Issue with welcome example

### ISSUE THREAD

**Issue by thijstriemstra** [rm-hull/ssd1306#99]
This is tested on osx py 3.5.1 with a broken pygame I suppose but this looks like a bug in the example:

```
$ PYTHONPATH=. python examples/welcome.py -d pygame
2016-12-15 18:53:40.032 python[6853:306148] 18:53:40.032 WARNING:  140: This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.
Traceback (most recent call last):
  File "examples/welcome.py", line 188, in <module>
    main()
  File "examples/welcome.py", line 162, in main
    for welcome_a, welcome_b in pairs(infinite_shuffle(welcome)):
  File "examples/welcome.py", line 107, in pairs
    last = generator.next()
AttributeError: 'generator' object has no attribute 'next'
```

**Comment by thijstriemstra** [comment]
Also happens with capture:

```
$ PYTHONPATH=. python examples/welcome.py -d capture
```
